# Generated by Django 4.2.3 on 2023-07-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
